In [39]:
import tensorflow as tf

In [40]:
import os
import pandas as pd
import tensorflow as tf
import numpy as np


In [41]:
# df=pd.read_csv("/content/toxicity_data_train.csv",sep=',*', header=[0])
df=pd.read_csv("/content/toxicity_data_train.csv",index_col = False,sep=",",)


In [42]:
df.head()

id                                       comment_text  toxic  \
0  0000997932d777bf  Explanation\nWhy the edits made under my usern...      0   
1  000103f0d9cfb60f  D'aww! He matches this background colour I'm s...      0   
2  000113f07ec002fd  Hey man, I'm really not trying to edit war. It...      0   
3  0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...      0   
4  0001d958c54c6e35  You, sir, are my hero. Any chance you remember...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0        0       0       0              0  
1             0        0       0       0              0  
2             0        0       0       0              0  
3             0        0       0       0              0  
4             0        0       0       0              0

In [43]:
df.tail()

id                                       comment_text  \
159566  ffe987279560d7ff  ":::::And for the second time of asking, when ...   
159567  ffea4adeee384e90  You should be ashamed of yourself \n\nThat is ...   
159568  ffee36eab5c267c9  Spitzer \n\nUmm, theres no actual article for ...   
159569  fff125370e4aaaf3  And it looks like it was actually you who put ...   
159570  fff46fc426af1f9a  "\nAnd ... I really don't think you understand...   

        toxic  severe_toxic  obscene  threat  insult  identity_hate  
159566      0             0        0       0       0              0  
159567      0             0        0       0       0              0  
159568      0             0        0       0       0              0  
159569      0             0        0       0       0              0  
159570      0             0        0       0       0              0

In [44]:
df.iloc[0]

id                                                0000997932d777bf
comment_text     Explanation\nWhy the edits made under my usern...
toxic                                                            0
severe_toxic                                                     0
obscene                                                          0
threat                                                           0
insult                                                           0
identity_hate                                                    0
Name: 0, dtype: object

In [45]:
df.iloc[2]['comment_text']

"Hey man, I'm really not trying to edit war. It's just that this guy is constantly removing relevant information and talking to me through edits instead of my talk page. He seems to care more about the formatting than the actual info."

In [46]:
df[df.columns[2:]].iloc[4]

toxic            0
severe_toxic     0
obscene          0
threat           0
insult           0
identity_hate    0
Name: 4, dtype: int64

In [47]:
from tensorflow.keras.layers import TextVectorization

In [48]:

X=df['comment_text']
y=df[df.columns[2:]].values

In [49]:
X.shape

(159571,)

In [50]:
y.shape

(159571, 6)

In [51]:
X

0         Explanation\nWhy the edits made under my usern...
1         D'aww! He matches this background colour I'm s...
2         Hey man, I'm really not trying to edit war. It...
3         "\nMore\nI can't make any real suggestions on ...
4         You, sir, are my hero. Any chance you remember...
                                ...                        
159566    ":::::And for the second time of asking, when ...
159567    You should be ashamed of yourself \n\nThat is ...
159568    Spitzer \n\nUmm, theres no actual article for ...
159569    And it looks like it was actually you who put ...
159570    "\nAnd ... I really don't think you understand...
Name: comment_text, Length: 159571, dtype: object

In [52]:
y

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [53]:
Max_feature=200000 #number of word in vocab
vectorizer=TextVectorization(max_tokens=Max_feature,
                             output_sequence_length=1800,
                             output_mode='int')

In [54]:
vectorizer.adapt(X.values)

In [55]:
vectorizer.get_vocabulary()

['',
 '[UNK]',
 'the',
 'to',
 'of',
 'and',
 'a',
 'you',
 'i',
 'is',
 'that',
 'in',
 'it',
 'for',
 'this',
 'not',
 'on',
 'be',
 'as',
 'have',
 'are',
 'your',
 'with',
 'if',
 'article',
 'was',
 'or',
 'but',
 'page',
 'my',
 'an',
 'from',
 'by',
 'do',
 'at',
 'about',
 'me',
 'so',
 'wikipedia',
 'can',
 'what',
 'there',
 'all',
 'has',
 'will',
 'talk',
 'please',
 'would',
 'its',
 'no',
 'one',
 'just',
 'like',
 'they',
 'he',
 'dont',
 'which',
 'any',
 'been',
 'should',
 'more',
 'we',
 'some',
 'other',
 'who',
 'see',
 'here',
 'also',
 'his',
 'think',
 'im',
 'because',
 'know',
 'how',
 'am',
 'people',
 'why',
 'edit',
 'articles',
 'only',
 'out',
 'up',
 'when',
 'were',
 'use',
 'then',
 'may',
 'time',
 'did',
 'them',
 'now',
 'being',
 'their',
 'than',
 'thanks',
 'even',
 'get',
 'make',
 'good',
 'had',
 'very',
 'information',
 'does',
 'could',
 'well',
 'want',
 'such',
 'sources',
 'way',
 'name',
 'these',
 'deletion',
 'pages',
 'first',
 'help'

In [56]:
vectorizer("Soumesh is Best") #numbers are represting index

<tf.Tensor: shape=(1800,), dtype=int64, numpy=array([  1,   9, 217, ...,   0,   0,   0])>

In [57]:
vectorizer_text=vectorizer(X.values)

In [58]:
vectorizer_text

<tf.Tensor: shape=(159571, 1800), dtype=int64, numpy=
array([[  645,    76,     2, ...,     0,     0,     0],
       [    1,    54,  2489, ...,     0,     0,     0],
       [  425,   441,    70, ...,     0,     0,     0],
       ...,
       [32445,  7392,   383, ...,     0,     0,     0],
       [    5,    12,   534, ...,     0,     0,     0],
       [    5,     8,   130, ...,     0,     0,     0]])>

In [59]:
input_tensor = tf.convert_to_tensor(vectorizer_text)
labels_tensor = tf.convert_to_tensor(y)

In [60]:
dataset=tf.data.Dataset.from_tensor_slices((input_tensor, labels_tensor))
dataset=dataset.cache()
dataset=dataset.shuffle(160000)
dataset=dataset.batch(16)
dataset=dataset.prefetch(8)

In [61]:
dataset.as_numpy_iterator().next()

(array([[  180,     4,  4393, ...,     0,     0,     0],
        [  204,  1280,    13, ...,     0,     0,     0],
        [   46,   168,    21, ...,     0,     0,     0],
        ...,
        [  242,   787,  2190, ...,     0,     0,     0],
        [   70,   265,    27, ...,     0,     0,     0],
        [27679,   728,     5, ...,     0,     0,     0]]),
 array([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]]))

In [62]:
batch_X,batch_y=dataset.as_numpy_iterator().next()

In [63]:
batch_X.shape

(16, 1800)

In [64]:
len(dataset)

9974

In [65]:
train=dataset.take(int(len(dataset)*.7))
val=dataset.skip(int(len(dataset)*.7)).take(int(len(dataset)*.2))
test=dataset.take(int(len(dataset)*.9)).take(int(len(dataset)*.1))

In [66]:
len(train),len(val),len(test)

(6981, 1994, 997)

In [67]:
train_generator=train.as_numpy_iterator().next()

In [68]:
train_generator

(array([[     2,    234,      9, ...,      0,      0,      0],
        [     8,     47,     67, ...,      0,      0,      0],
        [   729,   2384,     46, ...,      0,      0,      0],
        ...,
        [  1144,     31,  17608, ...,      0,      0,      0],
        [  5308,    308,  49382, ...,      0,      0,      0],
        [125195,    451,      3, ...,      0,      0,      0]]),
 array([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0],
        [1, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]]))

## CREATE A MODEL ( LSTM )

In [69]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM,Dropout,Bidirectional,Dense,Embedding

In [70]:
model=Sequential()
# we have to create a embedding layer
model.add(Embedding(Max_feature+1,32)) #vocab size,32 len vector of each word

model.add(Bidirectional(LSTM(32,activation='tanh')))

model.add(Dense(128,activation='relu'))
model.add(Dense(256,activation='relu'))
model.add(Dense(128,activation='relu'))
model.add(Dense(6,activation='sigmoid'))


In [71]:
model.compile(loss="BinaryCrossentropy",optimizer="adam")

In [72]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, None, 32)          6400032   
                                                                 
 bidirectional (Bidirectiona  (None, 64)               16640     
 l)                                                              
                                                                 
 dense (Dense)               (None, 128)               8320      
                                                                 
 dense_1 (Dense)             (None, 256)               33024     
                                                                 
 dense_2 (Dense)             (None, 128)               32896     
                                                                 
 dense_3 (Dense)             (None, 6)                 774       
                                                        

In [73]:
history=model.fit(train,epochs=1,validation_data=val)

6981/6981 [==============================] - 758s 107ms/step - loss: 0.0629 - val_loss: 0.0451


In [74]:
import pickle
with open("Toxic_model", 'wb') as f:
    pickle.dump(model, f)

## Make prediction

In [75]:
input_test=vectorizer("you freaking suck! I am going to hurt u")

In [76]:
res=model.predict(np.array([input_test]))

1/1 [==============================] - 1s 761ms/step


In [77]:
res

array([[0.9956735 , 0.36556447, 0.9599941 , 0.02933708, 0.80287975,
        0.16748063]], dtype=float32)

In [78]:
df.columns[2:]

Index(['toxic', 'severe_toxic', 'obscene', 'threat', 'insult',
       'identity_hate'],
      dtype='object')

## Evalute model

In [79]:
from tensorflow.keras.metrics import Precision,Recall,CategoricalAccuracy

In [80]:
pre=Precision()
re=Recall()
acc=CategoricalAccuracy()

In [82]:
for batch in test.as_numpy_iterator():
  X_true,y_true=batch
  y_hat=model.predict(X_true)

  y_true=y_true.flatten()
  y_hat=y_hat.flatten()

  pre.update_state(y_true,y_hat)
  re.update_state(y_true,y_hat)
  acc.update_state(y_true,y_hat)


1/1 [==============================] - 0s 55ms/step


In [83]:
print(pre.result().numpy(),re.result().numpy(),acc.result().numpy())

0.84275186 0.66125035 0.49448344


In [87]:
# !pip install gradio jinja2

In [85]:
import gradio as gr

In [86]:
model.save('toxicity.h5')

In [88]:
model=tf.keras.models.load_model('/content/toxicity.h5')

In [92]:
inp_test=vectorizer("hay i will kill u")
inp_test


<tf.Tensor: shape=(1800,), dtype=int64, numpy=array([13256,     8,    44, ...,     0,     0,     0])>

In [94]:
res=model.predict(np.array([inp_test]))

1/1 [==============================] - 1s 863ms/step


In [95]:
res

array([[0.64541703, 0.02192534, 0.22813024, 0.02862174, 0.2242131 ,
        0.04835058]], dtype=float32)

In [99]:
def score_comment(comment):
    vectorized_comment = vectorizer(comment)
    results = model.predict(np.array([vectorized_comment]))

    text = ''
    for idx, col in enumerate(df.columns[2:]):
        text += '{}: {}\n'.format(col, results[0][idx]>0.5)

    return text

In [100]:
score_comment("i will kill u")

1/1 [==============================] - 0s 83ms/step


'toxic: True\nsevere_toxic: False\nobscene: False\nthreat: False\ninsult: False\nidentity_hate: False\n'

In [101]:
interface = gr.Interface(fn=score_comment,
                         inputs=gr.inputs.Textbox(lines=2, placeholder='Comment to score'),
                        outputs='text')

<ipython-input-101-f5d8ac15336b>:2: GradioDeprecationWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  inputs=gr.inputs.Textbox(lines=2, placeholder='Comment to score'),
<ipython-input-101-f5d8ac15336b>:2: GradioDeprecationWarning: `optional` parameter is deprecated, and it has no effect
  inputs=gr.inputs.Textbox(lines=2, placeholder='Comment to score'),
<ipython-input-101-f5d8ac15336b>:2: GradioDeprecationWarning: `numeric` parameter is deprecated, and it has no effect
  inputs=gr.inputs.Textbox(lines=2, placeholder='Comment to score'),


In [102]:
interface.launch(share=True)

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
Running on public URL: https://913efa4f4f0301d90a.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
